#### MAC
# virtualenv venv && source ./venv/bin/activate
###WINDOWS
# virtualenv venv && .\venv\Scripts\activate


name: {{ cookiecutter.project_slug }} 
channels:
  - anaconda
  - defaults 
dependencies:
  - ipykernel
  - ipython
  {% if cookiecutter.project_packages == "All" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib 
  - keras
  - pytorch
  - tensorflow
  - pandas-flavor
  - pandas-profiling
  {% endif %}
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  {% if cookiecutter.project_packages == "All" -%}
  - pyproj root 
  {% endif %}
  - python = {{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.project_packages == "All" -%}
    - pyhere
    {% endif -%}